# Generated by Django 5.2.4 on 2025-07-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do evento (ex: Etapa 1 - Monza)', max_length=200)),
                ('track_name', models.CharField(help_text='Nome da pista', max_length=100)),
                ('event_date', models.DateField(help_text='Data do evento')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da equipe', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nome completo do piloto', max_length=150, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='Apelido do piloto', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, help_text='Nacionalidade do piloto', max_length=50, null=True)),
                ('team', models.ForeignKey(blank=True, help_text='Equipe à qual o piloto pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='league_manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(help_text='Modelo do carro utilizado', max_length=100)),
                ('final_position', models.PositiveIntegerField(help_text='Posição final na corrida')),
                ('best_lap_time', models.DurationField(blank=True, help_text='Melhor tempo de volta', null=True)),
                ('incidents', models.PositiveIntegerField(default=0, help_text='Número de incidentes')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Pontos conquistados na corrida')),
                ('raw_json_data', models.JSONField(default=dict, help_text='Dados brutos do arquivo JSON de resultado')),
                ('driver', models.ForeignKey(help_text='Piloto associado a este resultado', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='league_manager.driver')),
                ('event', models.ForeignKey(help_text='Evento ao qual este resultado pertence', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='league_manager.event')),
                ('team', models.ForeignKey(blank=True, help_text='Equipe do piloto na corrida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league_manager.team')),
            ],
            options={
                'ordering': ['final_position'],
                'unique_together': {('event', 'driver')},
            },
        ),
    ]
